services:
  app:
    image: mcr.microsoft.com/devcontainers/java:17
    volumes:
      - ../:/workspaces/${localWorkspaceFolderBasename}
    command: sleep infinity
    network_mode: service:db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/zinterview
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: zinterview
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
